# Generated by Django 5.2.8 on 2025-12-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_borrowed', models.SmallIntegerField()),
                ('interest', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=10)),
                ('user_surname', models.CharField(max_length=10)),
                ('user_birthday', models.DateField()),
                ('user_balance', models.SmallIntegerField()),
                ('unique_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
