# Generated by Django 5.2.8 on 2026-02-07 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='client',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='myfinalapp.user'),
        ),
    ]
