# Generated by Django 5.2.8 on 2026-02-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinalapp', '0002_credit_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_password',
            field=models.CharField(default='iiiiiiiiiii', max_length=10),
            preserve_default=False,
        ),
    ]
